---
kind: common.Image
name: image-release-tool
spec:
  extraEnvironment:
    PLATFORM: linux/amd64,linux/arm64
---
kind: common.Repository
spec:
  conformLicenseCheck: false
  licenses: []
---
kind: common.Image
name: image-release-tool
spec:
  baseImage: alpine:3.20
  additionalImages: []
  customCommands:
    - apk add --no-cache git git-lfs make sed
---
kind: service.CodeCov
spec:
  enabled: false
